### ISSUE TITLE
USER STORY: Short snippet on the Tailor

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#10]
As a **user**, I **would like to learn more about the people behind the business** so that **I can make up my mind if I would feel comfortable using their service**. 

## Acceptance Criteria

Acceptance Criteria 1:  A short description of the tailor
Acceptance Criteria 2:  An image of the tailor doing his craft
Acceptance Criteria 3:  A read more button that will link to the About page when clicked

## Tasks

- [x] Write the about section snippet
- [x] Find an image of the tailor
- [x] Code the section with the link to the About page

**Comment by MoniPar** [comment]
The link to the About Page will be added after the About, view, template and url have been created.
