### ISSUE TITLE
USER STORY: Section with Services snippet

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#11]
As a **business owner**, I **would like to display some of the services we provide on the homepage** so that **it gives the user an idea of the type of occasions we cater for**. 

## Acceptance Criteria

Acceptance Criteria 1:  Have a Services section which displays 2 or 3 different types of services.
Acceptance Criteria 2:  Have icons or images to display give a bit of visual feedback.
Acceptance Criteria 3:  Have a read more link that leads to the Services page

## Tasks

- [ ] Write the content
- [ ] Find images for the section or link Fontawesome for the icons
- [ ] Write the code and the link to the Services Page

**Comment by MoniPar** [comment]
This section will be added after creating the About view, template and url.
