### ISSUE TITLE
USER STORY: View Appointment

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#12]
As a **user**, I **would like to check my approved appointments** so that **I can organise my schedule and make myself available**. 

## Acceptance Criteria

Acceptance Criteria 1:  User will be able to see their past and future appointments listed
Acceptance Criteria 2:  User will be able to check if their future appointments have been approved

## Tasks

- [x] Create the Appointment Model
- [x] Create the Appointment View Code
- [x] Create the Appointment View Template
- [x] Connect up the URLs file
