### ISSUE TITLE
USER STORY: Admin Panel

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#13]
As a **business owner/admin**, I **would like to be able to login and view appointments scheduled by my customers** so that **I can contact them back for approval/dismissal**. 

## Acceptance Criteria

Acceptance Criteria 1: Admin has the facility to login to the Admin Panel
Acceptance Criteria 2: Admin can view users/customers details and appointments
Acceptance Criteria 3: Admin can approve or dismiss appointments set by the user/customer

## Tasks

- [x] Create Super User
- [x] Register Appointment model to admin site
- [x] Add action to approve appointments

**Comment by MoniPar** [comment]
Admin panel, `search_fields`  by date does not work as expected.  If month is inserted, no results are found.  Only integers give a result.
