### ISSUE TITLE
USER STORY: Create Appointments

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#14]
As a **user**, I **would like to be able to schedule an appointment with the master tailor** so that **I can decide if I want to go ahead with using Tailor's Thimble services**. 

## Acceptance Criteria

Acceptance Criteria 1: Form will have all the necessary fields to complete appointment schedule.
Acceptance Criteria 2: Form will have information on how to schedule an appointment.
Acceptance Criteria 3: Submit button will direct user to the 'appointments' page, which shows all scheduled appointments.

## Tasks

- [x] Create the Appointment view.
- [x] Link up the urls.
- [x] Create the Appointment form template.
- [x] Override the form_valid method to add the current logged in user before form is submitted.
- [x] Create a get_absolute_url method to return the path to the 'appointments' page.
