### ISSUE TITLE
USER STORY: Delete Appointment

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#16]
As a **user**, I **would like the ability to delete my upcoming appointment** so that **I can reschedule at a later date**. 

## Acceptance Criteria

Acceptance Criteria 1: User has the functionality to delete an upcoming appointment from the 'appointment-detail' page.
Acceptance Criteria 2: When user clicks on delete button, they are directed to a confirmation page with 'delete' and 'cancel' buttons.
Acceptance Criteria 3: If user clicks cancel, they are brought back to the 'appointment-detail' page of the current appointment.
Acceptance Criteria 4: If user clicks delete, the appointment is deleted and user is directed back to the 'appointments' page.
 

## Tasks

- [x] Create the Delete Appointment View Code
- [x] Add the Delete Appointment Button
- [x] Create the Alert Deletion Confirmation Template
- [x] Connect the urls

**Comment by MoniPar** [comment]
All works good, need success messages.
