### ISSUE TITLE
USER STORY: Registration

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#17]
As a **user**, I **would like to be able to register an account** so that **I can make an appointment with the master tailor**. 

## Acceptance Criteria

Acceptance Criteria 1: A new user will be directed to the registration form when they click the 'Schedule Appointment' button.
Acceptance Criteria 2: The form will have fields for username and password and a submit button.  
Acceptance Criteria 3: Once the submit button is clicked, user will be redirected to the homepage.

## Tasks

- [x] Create the User app and add it to INSTALLED_APPS
- [x] Install and configure 'Django allauth' 
- [x] Configure settings.py
- [x] Modify the signup.html template
- [x] Add conditional to 'Schedule Appointment' button for unregistered user to be directed to signup page.
