### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#18]
As a **user**, I **can use my username and password** so that **I can login to my user account**. 

## Acceptance Criteria

Acceptance Criteria 1:  Users are directed to the login form when they click on the link in the navbar 
Acceptance Criteria 2: Login form will include the 'django-allauth' default fields.
Acceptance Criteria 3: After login, user is directed back to the home page.

## Tasks

- [x] Connect up the 'sign in' URL template to the navbar link.
- [x] Add conditionals to show logout link when user is logged in.
- [x] Modify the 'sign in' template
