### ISSUE TITLE
USER STORY: Create the Django project and app

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#2]
As a **developer**, I **need to create the Django project and app** so that **I can set up the database**. 

## Acceptance Criteria

Acceptance Criteria 1: The Django project directory has been successfully created.
Acceptance Criteria 2: The core app has been successfully created.
Acceptance Criteria 3: The basic skeleton project is up and running.

## Tasks

- [x] Create the Django project
- [x] Create the core app
- [x] Add it to the list of installed apps
- [x] Migrate the changes to the database
