### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#20]
As a **user**, I **would like to be able to have access to my information** so that **I can view my details**. 

## Acceptance Criteria

Acceptance Criteria 1: Registered users will be able to check their details and add more information about their requirements in the Profile page.
Acceptance Criteria 1: A profile of the user is created upon registration.
Acceptance Criteria 2: A freshly registered user will be directed to the profile page after registration.
Acceptance Criteria 3: A logged user can click on the 'User' Profile link in the navbar and be directed to their Profile page.

## Tasks

- [x] Create the profile view
- [x] Create the profile template
- [x] Create the route
- [x] Link to navigation
- [x] Restrict route to logged in users
- [x] Create the Profile Model
- [x] Register the Profile Model
- [x] Automate Profile creation upon registration

**Comment by MoniPar** [comment]
No change password feature
Date field needs a datepicker or placeholder text to show user how to format date for validation 
Needs placeholders or hints about what to put in occasion type and requirements boxes.
