### ISSUE TITLE
USER STORY: Update User Profile

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#22]
As a **user**, I **would like to be able to update my profile** so that **I can change my details when necessary**. 

## Acceptance Criteria

Acceptance Criteria 1:  Profile Page will be an editable form with fields already filled in with user's current information.
Acceptance Criteria 2: Fields included will be 'username', 'first name', 'last name', 'email' & 'phone', 'occasion date', 'occasion type', ' occasion requirement'.  
Acceptance Criteria 3: Form will have an 'Update Profile' button.
Acceptance Criteria 4: Form is validated before saved and user is alerted to required fields/invalid inputs.
Acceptance Criteria 5: User will be directed back to Profile page after successful update which will show the newly entered information.

## Tasks

- [x] Create 'UserUpdateForm' and 'ProfileUpdateForm'
- [x] Add forms to view
- [x] Update the profile template
- [x] Update the profile view
