### ISSUE TITLE
USER STORY: Cloudinary Setup

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#4]
As a **developer**, I **need to set up and connect the project to Cloudinary** so that **I can upload images to a persistent file store**. 

## Acceptance Criteria

Acceptance Criteria 1: The project has been connected to Cloudinary successfully.
Acceptance Criteria 2: Heroku has been connected to Cloudinary successfully.
Acceptance Criteria 3: Media and Static files have been configured to be stored on Cloudinary.

## Tasks

- [x] Add Cloudinary API environment variable to env.py and Heroku
- [x] Set DISABLE_COLLECTSTATIC on Heroku
- [x] Add Cloudinary Libraries to INSTALLED_APPS in settings.py
- [x] Set Cloudinary as storage for media and static files in settings.py
