### ISSUE TITLE
USER STORY: Preparation and Deployment

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#5]
As a **developer**, I **need to give Django some more specific instructions** so that **the project is deployed successfully**. 

## Acceptance Criteria

Acceptance Criteria 1: Django knows where the templates are stored.
Acceptance Criteria 2: Django knows where the project is being hosted.
Acceptance Criteria 3: The project has been deployed successfully.

## Tasks

- [x] Set up the templates directory in settings.py
- [x] Add the Heroku host name into ALLOWED_HOSTS in settings.py
- [x] Create the media, static and templates directories
- [x] Create a Procfile
- [x] Deploy
