### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#8]
As a **user**, I **would like to see contact details, shop address and social links at the bottom of the website** so that **I can follow/contact the business owner and the website creator**. 

## Acceptance Criteria

Acceptance Criteria 1: A footer is displayed at the bottom of the page
Acceptance Criteria 2: Contact details, social links and shop address are clearly displayed
Acceptance Criteria 3: Copyright date and link to the website creator's LinkedIn page opens in a new page.

## Tasks

- [x] Add footer to the base template
- [x] Use Bootstrap 4 to create a responsive footer
- [x] Add information and links to social media to open in a new tab
