### ISSUE TITLE
USER STORY: Call to Action

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/django-a-go#9]
As a **business owner**, I **would like the homepage to have an eye catching Appointment button ** so that **users are encouraged to schedule an appointment early on**. 

## Acceptance Criteria

Acceptance Criteria 1:  A hero image that draws the eye to the Schedule an Appointment Button
Acceptance Criteria 2: Button will eventually link to the Booking Form
Acceptance Criteria 3

## Tasks

- [x] Find an appropriate Hero image
- [x] Write the text that overlays the image
- [x] Create the button and the link

**Comment by MoniPar** [comment]
Link will be created later when the form is ready!
